### ISSUE TITLE
!nasa does not return an image

### ISSUE THREAD

**Issue by Patross** [AndyTheNerd/Storehaus#17]
Possible cause might be the nasa api returning a video as seen in bot logs
![image](https://user-images.githubusercontent.com/24960230/92992382-65725780-f4e2-11ea-94c9-6584b34ca9d6.png)

**Comment by AndyTheNerd** [comment]
This has been fixed in a new commit. Yay

**Comment by Patross** [comment]
Reopening as the recent commit affected different part of NASA.js 

This issue is still valid

**Comment by AndyTheNerd** [comment]
NASA also does not work if a video is returned

**Comment by AndyTheNerd** [comment]
K it closed on accident
